### PR TITLE
fixes for flash and html uploader

### PR DESCRIPTION
**Pull request by magp3**

### CODE REVIEW

**Comment by douglascrp** [comment]
@magp3 What is the Alfresco version you are working on?
I tried to use your code version, and when I access a folder configured for uploader-plus, I see the message bellow in the browser's console.

Uncaught TypeError: Alfresco.getFileUploadInstance is not a function

This happens exactly inside the files you changed:
alfresco/site-webscripts/com/softwareloop/uploader-plus/uploader/html-upload.get.html.ftl
alfresco/site-webscripts/com/softwareloop/uploader-plus/uploader/flash-upload.get.html.ftl

In this case, I was testing on a 5.0.d server.

**Comment by magp3** [comment]
@douglascrp I'm using 5.1.
That is strange, works for me. Is your DNDUploader working? 
Because the DNDUploader executes getFileUploadInstance aswell.

**Comment by douglascrp** [comment]
@magp3 No, it's not working also.

**Comment by douglascrp** [comment]
@magp3 Just after writing the last comment, I decided to try again, but this time, executing the SDK project using maven.
Same thing, same error messages, and drag and drop is not working also.
So, it's not specific for 5.0.d, as the project is now based on 5.1.e.

**Comment by magp3** [comment]
@douglascrp I see. Maybe it does not work on community? Because I use the DNDUploader on
5.0.0 Enterprise and 5.1 Enterprise without issues.

**Comment by douglascrp** [comment]
@magp3 Can you try it against a community server yourself?

**Comment by douglascrp** [comment]
@magp3 Hey, have you had the opportunity to test the addon?

**Comment by magp3** [comment]
@douglascrp I tested v1.2 (the one on maven, which doesn't have these fixes) on community 5.1. And it seems these fixes are only required for Enterprise(?) I'm making a new pull request which I believe solves the issue you're having..

**Pull request closed without merging**
